import sys
from pathlib import Path
import plotly.express as px

project_root = Path(__file__).resolve().parent.parent

if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

from workflow.langgraph_orchestrator import app
import streamlit as st

from services.finance_service import get_financial_summary

from services.analytics_service import get_monthly_revenue

from services.customer_service import get_customer_segments

from services.product_service import get_top_products

from utils.pdf_generator import generate_pdf_report

st.markdown("""
<style>
div[data-testid="metric-container"] {
    background-color: #2563eb;
    padding: 15px;
    border-radius: 12px;
}
</style>
""", unsafe_allow_html=True)

st.set_page_config(
    page_title="Multi-Agent BI Platform",
    layout="wide"
)

if "messages" not in st.session_state:
    st.session_state.messages = []

@st.cache_data(ttl=60)
def get_ai_summary():
    summary = app.invoke(
        {
            "question": "Generate an executive summary"
        }
    )
    return summary
with st.sidebar:

    st.title("Navigation")

    st.write("Multi-Agent BI Platform")

    st.markdown("---")

    st.write("Data Warehouse")
    st.write("Analytics")
    st.write("AI Agents")
    st.write("RAG Knowledge Base")

st.title(
    "Multi-Agent Business Intelligence Platform"
)

st.subheader(
    "Executive KPI Overview"
)

customer_df = get_customer_segments()

product_df = get_top_products()

finance = get_financial_summary()

revenue = finance["total_revenue"].iloc[0]
profit = finance["total_profit"].iloc[0]
margin = finance["profit_margin"].iloc[0]
total_customers = customer_df["customers"].sum()

col1, col2, col3, col4 = st.columns(4)

with col1:
    st.metric(
        "Revenue",
        f"${revenue:,.0f}"
    )

with col2:
    st.metric(
        "Profit",
        f"${profit:,.0f}"
    )

with col3:
    st.metric(
        "Profit Margin",
        f"{margin:.2f}%"
    )

with col4:
    st.metric(
        "Customers",
        f"{total_customers:,}"
    )

top_product = product_df.iloc[0]["product_name"]
top_revenue = product_df.iloc[0]["revenue"]

st.success(
    f"Top Revenue Product: {top_product} (${top_revenue:,.2f})"
)

st.subheader("Executive Summary")

with st.spinner("Generating executive summary..."):

    summary = get_ai_summary()

    # st.code(summary["answer"])

summary_text = (summary["answer"].replace("*", "").replace("#", ""))

summary_text = (
    summary_text
    .replace("**", "")
    .replace("*", "")
    .replace("#", "")
)

summary_text = summary_text.replace(
    "# Executive Summary",
    ""
)

summary_text = summary_text.replace(
    "Executive Summary",
    ""
)

summary_text = summary_text.strip()

with st.container(border=True):

    st.text(summary_text)

    st.caption("🤖 Generated by Executive Agent")

revenue_df = get_monthly_revenue()

revenue_df["period"] = (
    revenue_df["year"].astype(str)
    + "-"
    + revenue_df["month"].astype(str).str.zfill(2)
)

fig = px.line(
    revenue_df,
    x="period",
    y="revenue",
    title="Monthly Revenue Trend"
)

fig.update_layout(
    xaxis_title="Period",
    yaxis_title="Revenue ($)",
    template="plotly_white",
    height=500

)

st.plotly_chart(
    fig,
    use_container_width=True
)


col1, col2 = st.columns(2)

with col1:

    st.subheader("Revenue by Segment")

    fig = px.bar(
        customer_df,
        x="segment",
        y="revenue"
    )

    fig.update_layout(
        xaxis_title="Customer Segment",
        yaxis_title="Revenue ($)",
        template="plotly_white"
    )

    st.plotly_chart(
        fig,
        use_container_width=True
    )

with col2:

    st.subheader("Top Products")

    display_df = product_df.copy()

    display_df["revenue"] = display_df["revenue"].map(
        lambda x: f"${x:,.2f}"
    )

    st.dataframe(
        display_df,
        use_container_width=True,
        hide_index=True
    )

pdf_file = generate_pdf_report(
    revenue,
    profit,
    margin,
    total_customers,
    top_product,
    customer_df.iloc[0]["segment"]
)

with open(pdf_file, "rb") as pdf:

    st.download_button(
        label="📄 Download Executive Report",
        data=pdf,
        file_name="executive_report.pdf",
        mime="application/pdf"
    )
st.divider()

st.subheader(
    "AI Business Analyst"
)

for msg in st.session_state.messages:

    with st.chat_message(msg["role"]):

        if msg["role"] == "assistant":
            st.caption(
                f"🤖 Agent Used: {msg['agent']}"
            )

        st.markdown(
            msg["content"]
        )

question = st.chat_input(
    "Ask a business question..."
)

if question:

    with st.spinner("Analyzing..."):

        result = app.invoke(
            {
                "question": question
            }
        )

    agent_used = result["agent"]

    st.session_state.messages.append(
        {
            "role": "user",
            "content": question
        }
    )

    st.session_state.messages.append(
        {
            "role": "assistant",
            "content": result["answer"],
            "agent": agent_used
        }
    )

    st.rerun()

